---
title: "Untitled"
author: "Kwangmin Kim"
date: '2022 1 3 '
output:
  pdf_document: default
header-includes:
    - \usepackage{kotex}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Markdown Syntax

테스트. 본문의 제목은 항상 heading 2 즉 `##`을 사용해야한다.

### `#`을 사용한 제목 설정

`#`을 사용하면 제목을 다양하게 설정할 수 있다.

# 제목 1
## 제목 2
### 제목 3
#### 제목 4
##### 제목 5
###### 제목 6
####### 제목 7

### 본문을 강조하는 방법

이텔릭: 본문에 이탤릭을 사용하고 싶다면 *별표 1개를 해당 단어 양옆에 적음*

bold : 굴게 표시하고 싶다면 **별표2개를 해당 단어 양옆에 적음**

교정기호 : 교정기호를 사용하고 싶다면 ~~물결 표시2개를 해당 단어 양옆에 적음 ~~

### 본문에 리스트 넣는 법

본문에 넣을 수 있는 리스트의 종류는 두가지.

첫 번째. 숫자가 있는 리스트

예1)좋아하는 과일 순위: 숫자 여러개로 리스팅

1. 딸기
2. 바나나
3. 사과 

예2)좋아하는 과일 순위: 숫자 하나로 리스팅

1. 딸기
1. 바나나
1. 사과 
    1. 맛있어
    1. 달어
    1. 셔
1. 수박

숫자 하나로 리스팅하는 것이 더 편함. 장문의 글이나 리스팅을 작성할 때 수정사항이 생기면
리스팅 번호를 바꿀 필요가 없기 때문.

두 번째. 숫자가 없는 리스트

예1)좋아하는 과일 순위: 기호로 리스팅

* 딸기
* 바나나
* 사과
    - 맛있어
    - 달어
    - 셔
* 수박박

### 본문에 수학 모드로 입력하기

수학 모드로 변환하고 싶다면 $dollar 사인1개를 해당글 양옆에$ 입력

* 본문 안에서 숫자 혹은 수식 입력: `$` 기호 $1$개로 둘러쌈
* 본문 밖에서 가운데 정렬 후 숫자 혹은 수식 입력: `$` 기호 $2$개로 둘러쌈 : display 서식으로 줄 바꿈후 사용하는 것이 좋다.

예를 들어, 우리가 $$1$$개의 사과를 구입했다고 생각.
예를 들어, 수식 입력은 다음과 같다.
$$\int_{1}^{10}x dx$$

### 구글에 R markdown cheetsheet

### 본문에 테이블 넣기

Table Header | Second Header
-------------|---------------
table cell   |  cell 2
cell 3       |  cell 4

### theme 적용

위 yaml에 작성.
현재 theme은 html_document 에서 만 적용되는 것처럼 보임

예)
html_document:
    theme: readable